export const PULSE_METRICS = {
  vix: {
    id: 'vix',
    label: 'VIX',
    description: 'Índice de miedo del mercado de acciones',
    source: 'FRED',
    seriesId: 'VIXCLS',
    ttlHours: 6,
    thresholds: {
      green: { max: 15, label: 'Calma' },
      yellow: { min: 15, max: 25, label: 'Normal' },
      orange: { min: 25, max: 35, label: 'Tensión' },
      red: { min: 35, label: 'Pánico' },
    },
    unit: '',
    higherIsBad: true,
  },
  fearGreed: {
    id: 'fearGreed',
    label: 'Fear & Greed',
    description: 'Sentimiento del mercado crypto (0=miedo, 100=codicia)',
    source: 'alternative.me',
    ttlHours: 12,
    thresholds: {
      red: { max: 25, label: 'Miedo extremo' },
      orange: { min: 25, max: 45, label: 'Miedo' },
      yellow: { min: 45, max: 55, label: 'Neutral' },
      green: { min: 55, max: 75, label: 'Codicia' },
      red2: { min: 75, label: 'Codicia extrema' },
    },
    unit: '/100',
    higherIsBad: false,
  },
  dxy: {
    id: 'dxy',
    label: 'DXY',
    description: 'Índice de fortaleza del dólar USD',
    source: 'Yahoo',
    ticker: 'DX-Y.NYB',
    ttlHours: 6,
    thresholds: {
      green: { max: 100, label: 'Dólar débil (bueno para crypto/oro)' },
      yellow: { min: 100, max: 104, label: 'Dólar fuerte' },
      red: { min: 104, label: 'Dólar muy fuerte (presión sobre activos)' },
    },
    unit: '',
    higherIsBad: true,
  },
  eurusd: {
    id: 'eurusd',
    label: 'EUR/USD',
    description: 'Tipo de cambio euro-dólar',
    source: 'ExchangeRate',
    ttlHours: 6,
    unit: '',
    higherIsBad: false,
  },
  us10y: {
    id: 'us10y',
    label: 'US 10Y',
    description: 'Rendimiento del bono americano a 10 años',
    source: 'FRED',
    seriesId: 'DGS10',
    ttlHours: 6,
    thresholds: {
      green: { max: 3.5, label: 'Tipos bajos (favorable para acciones)' },
      yellow: { min: 3.5, max: 4.5, label: 'Tipos moderados' },
      red: { min: 4.5, label: 'Tipos altos (presión sobre growth y crypto)' },
    },
    unit: '%',
    higherIsBad: true,
  },
  gold: {
    id: 'gold',
    label: 'Oro',
    description: 'Precio del oro en USD por onza troy',
    source: 'Yahoo',
    ticker: 'GC=F',
    ttlHours: 6,
    unit: '$',
    higherIsBad: false,
  },
  bitcoin: {
    id: 'bitcoin',
    label: 'Bitcoin',
    description: 'Precio de Bitcoin en USD',
    source: 'CoinGecko',
    coinId: 'bitcoin',
    ttlHours: 1,
    unit: '$',
    higherIsBad: false,
  },
  m2: {
    id: 'm2',
    label: 'M2 USA',
    description: 'Masa monetaria M2 de USA. Expansión = favorable para activos',
    source: 'FRED',
    seriesId: 'M2SL',
    ttlHours: 24,
    unit: 'T$',
    higherIsBad: false,
  },
} as const;

export type PulseMetricId = keyof typeof PULSE_METRICS;

export const ALERT_THRESHOLDS = {
  vix_spike: { metric: 'vix', operator: '>', value: 35 },
  vix_low: { metric: 'vix', operator: '<', value: 12 },
  fear_greed_fear: { metric: 'fearGreed', operator: '<', value: 20 },
  fear_greed_greed: { metric: 'fearGreed', operator: '>', value: 80 },
  dxy_strong: { metric: 'dxy', operator: '>', value: 107 },
  us10y_high: { metric: 'us10y', operator: '>', value: 5.0 },
} as const;
